### ISSUE TITLE
`apmperf`: panic slice out of bounds

### ISSUE THREAD

**Issue by inge4pres** [elastic/apm-perf#75]
**Describe the bug**

Encountered this panic when running apmsoak in the tilt/AWS setup

```
{"log.level":"error","@timestamp":"2024-03-19T14:54:09.768Z","log.logger":"soaktest","log.origin":{"function":"github.com/elastic/apm-perf/internal/loadgen/eventhandler.logResponseOutcome","file.name":"eventhandler/apm.go","file.line":90},"message":"request failed","status_code":401,"response":"{\"message\":\"Unauthorized\"}\n","ecs.version":"1.6.0"}
panic: runtime error: slice bounds out of range [1267810:759964]

goroutine 21 [running]:
bytes.(*Buffer).Bytes(...)
	/usr/local/go/src/bytes/buffer.go:54
net/http.NewRequestWithContext({0x26893d8?, 0x40001440f0}, {0x43673f?, 0x0?}, {0x400012a1b0?, 0x30?}, {0x2685380, 0x40000b4040?})
	/usr/local/go/src/net/http/request.go:876 +0x670
github.com/elastic/apm-perf/internal/loadgen/eventhandler.(*APMTransport).SendEvents(0x400011ca80, {0x26893d8?, 0x40001440f0?}, {0x2685380, 0x40000b4040}, 0x0?)
	/opt/apm-perf/internal/loadgen/eventhandler/apm.go:50 +0x60
github.com/elastic/apm-perf/internal/loadgen/eventhandler.(*Handler).sendBatch(0x400014a0c0, {0x26893d8, 0x40001440f0}, 0x40000a5b60, {{0x4001ab2240, 0x23b, 0x23b}, {0x4004e00000, 0xea9, 0x1300}}, ...)
	/opt/apm-perf/internal/loadgen/eventhandler/handler.go:358 +0x450
github.com/elastic/apm-perf/internal/loadgen/eventhandler.(*Handler).sendBatches(0x400014a0c0, {0x26893d8, 0x40001440f0}, 0x40000a5b60)
	/opt/apm-perf/internal/loadgen/eventhandler/handler.go:307 +0x390
github.com/elastic/apm-perf/internal/loadgen/eventhandler.(*Handler).SendBatchesInLoop(0x400014a0c0, {0x26893d8, 0x40001440f0})
	/opt/apm-perf/internal/loadgen/eventhandler/handler.go:269 +0x74
github.com/elastic/apm-perf/internal/soaktest.runAgent({0x26893d8, 0x40001440f0}, 0x4000126480, {{0x400013c140, 0x20}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...)
	/opt/apm-perf/internal/soaktest/runner.go:127 +0x204
github.com/elastic/apm-perf/internal/soaktest.(*Runner).Run.func1()
	/opt/apm-perf/internal/soaktest/runner.go:103 +0x128
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78 +0x5c
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:75 +0x9c
```

**Comment by inge4pres** [comment]
Another one found in a more recent version

```
panic: runtime error: slice bounds out of range [923765:757053]

goroutine 54 [running]:
bytes.(*Buffer).Bytes(...)
	/usr/local/go/src/bytes/buffer.go:54
net/http.NewRequestWithContext({0x2c52410?, 0x400003c080}, {0x97c3f3?, 0x0?}, {0x400003a930?, 0x30?}, {0x2c474a0, 0x4000332040?})
	/usr/local/go/src/net/http/request.go:876 +0x670
github.com/elastic/apm-perf/internal/loadgen/eventhandler.(*APMTransport).SendEvents(0x4000116270, {0x2c52410?, 0x400003c080?}, {0x2c474a0, 0x4000332040}, 0x0?)
	/opt/apm-perf/internal/loadgen/eventhandler/apm.go:50 +0x60
github.com/elastic/apm-perf/internal/loadgen/eventhandler.(*Handler).sendBatch(0x4000190000, {0x2c52410, 0x400003c080}, 0x4000355ef0, {{0x4003ed4000, 0x23b, 0x23b}, {0x4004e80000, 0xea9, 0x1300}}, ...)
	/opt/apm-perf/internal/loadgen/eventhandler/handler.go:358 +0x450
github.com/elastic/apm-perf/internal/loadgen/eventhandler.(*Handler).sendBatches(0x4000190000, {0x2c52410, 0x400003c080}, 0x4000355ef0)
	/opt/apm-perf/internal/loadgen/eventhandler/handler.go:307 +0x390
github.com/elastic/apm-perf/internal/loadgen/eventhandler.(*Handler).SendBatches(0x4000190000, {0x2c52410, 0x400003c080})
	/opt/apm-perf/internal/loadgen/eventhandler/handler.go:288 +0x58
main.benchmarkAgent.func1(0x400019c160)
	/opt/apm-perf/cmd/apmbench/bench.go:152 +0xbc
testing.(*B).RunParallel.func1()
	/usr/local/go/src/testing/benchmark.go:815 +0xbc
created by testing.(*B).RunParallel
	/usr/local/go/src/testing/benchmark.go:808 +0xf0

```

**Comment by vikmik** [comment]
When we send an http request, when there's an error the client will return as soon as possible, but it doesn't mean the http round tripper is finished reading the request body ([it might still be reading from our writer](https://github.com/golang/go/blob/58c5db3169c801737cb0e0ed4886554763c861eb/src/net/http/transport.go#L2669)).

In practice, it means that the request body we give to the HTTP client should be considered immutable afterwards - otherwise we can introduce race conditions. But our code doesn't do that - we get a `pooledWriter`  from `writerPool`  which has an underlying `bytes.Buffer`, then we potentially use the `pooledWriter` for multiple requests (it's used in a loop [here](https://github.com/elastic/apm-perf/blob/4071c2ab73188fae0e71a5fbcda72d3043f002a4/internal/loadgen/eventhandler/handler.go#L345)) (the `bytes.Buffer` is `s.w.buf`).

This means we potentially have an HTTP roundtripper reading from the `bytes.Buffer` (changing its offset) while we write to it at the same time from the APM handler, which can grow the underlying slice - it's all undefined behavior. Then, the next time the buffer is used as a request body, the offset and length of the slice may be non-sensical, and [this call](https://github.com/golang/go/blob/58c5db3169c801737cb0e0ed4886554763c861eb/src/net/http/request.go#L929) to `bytes.Buffer.Bytes()` panics because the offset is greater than the length.

Interestingly I can only reproduce on x86. Tilt seems to build aarch64 binaries by default on my machine (which works out of the box with my qemu setup) and I did not encounter the bug on arm64.
